### ISSUE TITLE
Problems with constructor when using from NPM

### ISSUE THREAD

**Issue by evolross** [taufik-nurrohman/color-picker#38]
When I try to use this package via NPM, I install it and then import with an ECMAScript style import like:

`import { CP } from 'c-p';`

I can see all the `CP` static functions on a global `CP` object when investigating in Chrome's DevTools and I can call them and they work (e.g. `CP.HEX2HSV`), but when I try to call:

`let picker = new CP(...);`

I get an error message saying "Uncaught TypeError: CP is not a constructor".  If I just move the color-picker.min.js file into my project, don't import and just use it as a global, everything works fine.

Any ideas?

**Comment by tovic** [comment]
Not an NPM guy (and all that package manager stuff). Does the import system make the `CP` scope moved to private? Because I always put my plugin name to the `window` scope.

**Comment by evolross** [comment]
It puts `CP` in the global `window` scope correctly.  That works and I can call all the static functions like `CP.HEX2HSV`, etc.  

I just can't call `new CP(...)` which is what I need to actually created the color picker. I'm actually not using any of the static functions.

**Comment by taufik-nurrohman** [comment]
This issue should be fixed since now I am using Rollup.

~~~ js
import CP from '@taufik-nurrohman/color-picker';

let picker = new CP(document.querySelector('input'));
~~~
