### ISSUE TITLE
TODO: Alpha Channel Support

### ISSUE THREAD

**Issue by taufik-nurrohman** [taufik-nurrohman/color-picker#51]
There is no need to change the API. Just add the alpha value to the converter result next to the blue field (default to `1`, ranged from `0` to `1`):

 - `[r, g, b, a = 1]`
 - `[h, s, v, a = 1]`
 - `rrggbb(aa)?`

**Comment by maifeeulasad** [comment]
@taufik-nurrohman , I'm interested fixing this one ? Can I get assigned in this ?

**Comment by sabuz** [comment]
If you add this feature, I'll add this color picker in my upcoming page builder

**Comment by taufik-nurrohman** [comment]
Not as soon as one month later, but also will not be longer than 4 months to come. I am currently working on [@taufik-nurrohman/tag-picker](https://github.com/taufik-nurrohman/tag-picker), [@taufik-nurrohman/text-editor](https://github.com/taufik-nurrohman/text-editor) and [@mecha-cms/x.panel](https://github.com/mecha-cms/x.panel) that depends on those plugins.

**Comment by sabuz** [comment]
If this don't take more than 4 months, then I'm keen to use the current version in my alpha release.

**Comment by taufik-nurrohman** [comment]
I am thinking about another approach for the next color picker release. As it is now possible to store alpha channel to a HEX color, maybe the color parser logic of the core version can be reduced to only be able to parse one type of color mode (which I think it would be HEX as it was the most compact and easy-to-type color mode compared to RGB and HSL). The sample API would become like this:

~~~ .js
var picker = new CP(source, {
        color: 'HEX', // Default color mode
        on: ['click', 'focus', 'touchstart']
    });

// Backward compatibility
var picker = new CP(source, ['click', 'focus', 'touchstart']);
~~~

Color modes will be stored to the color picker&rsquo;s `color` object as static functions that accepts a string input (that would be parsed into array of _red_, _green_, _blue_, and _alpha_ data in the output) or an array input contains _red_, _green_, _blue_, and _alpha_ data (that would be parsed into a color string):

~~~ .js
CP.color.HEX = function(x) {
    if ('string' === typeof x) {
        var r, g, b, a = 1;
        // Convert to `[r, g, b, a]` etc.
        return [r, g, b, a];
    }
    var str = "";
    // Convert to `#rrggbbaa` etc.
    return '#' + str;
};

// Static usage
var a = CP.color.HEX('#ffffff');
var b = CP.color.HEX([255, 255, 255]);

console.log(a); // `[255, 255, 255, 1]`
console.log(b); // `"#ffffff"`
~~~

To create another color mode support, just add new static function to the `CP.color` object and apply it to the `color` option later. These can be created in separate extensions:

~~~ .js
CP.color.CMYK = function(x) {};
CP.color.HSL = function(x) {};
CP.color.RGB = function(x) { … };

var picker = new CP(source, {
        color: 'RGB'
    });
~~~

There is a great possibility to create automatic color mode simply by adding `auto` to the `color` object and then do your color mode detection there. This can be created in a separate extension:

~~~ .js
CP.color.auto = function(x) {
    if ('string' === typeof x) {
        if (0 === x.indexOf('hsl')) {
            return CP.color.HSL(x);
        }
        if (0 === x.indexOf('rgb') {
            return CP.color.RGB(x);
        }
        // Default to `HEX`
        return CP.color.HEX(x);
    }
};

// Usage
var picker = new CP(source, {
        color: 'auto'
    });
~~~

So, for example:

~~~ .html
<script src="color-picker.js"></script>
<script src="color-picker/c-m-y-k.js"></script>
<script src="color-picker/h-s-l.js"></script>
<script src="color-picker/r-g-b.js"></script>
<script src="color-picker/auto.js"></script>
<script>
var source = document.querySelector('input'),
    picker = new CP(source, {
        color: 'auto'
    });
    picker.on('change', function(r, g, b, a) {
        this.source.value = CP.color.auto([r, g, b, a]);
    });
</script>
~~~

**Comment by taufik-nurrohman** [comment]
Done!

https://github.com/taufik-nurrohman/color-picker/releases/tag/v2.0.0
