### ISSUE TITLE
Remove "#" from the input

### ISSUE THREAD

**Issue by arsenkolyba** [taufik-nurrohman/color-picker#54]
I'm using the color picker and it's great. One thing I can't figure out on my own is how to remove the "#" from inputs value.

Obviously I did this:
`this.source.value = color;`
instead of 
`this.source.value = "#" + color;`

And that works just fine, there is no "#" left in the input and the picker works as expected. **The thing that's broken** is being able to manually enter or paste a HEX value into the input.

I didn't have any success fixing this so my only hope is you man :(

**Comment by taufik-nurrohman** [comment]
Try to tweak it yourself maybe?

``` js
hex = x.match(/^#?([\da-f]{3}|[\da-f]{6})$/i);

if (hex) {
    return HEX2HSV(x);
}
```

https://github.com/taufik-nurrohman/color-picker/blob/9b4843866bac28ab3706a1e2bb41c60cc02894b2/color-picker.js#L155&L157

**Comment by arsenkolyba** [comment]
Works like a charm, thank you!
