### ISSUE TITLE
Change Hook Running On Init

### ISSUE THREAD

**Issue by mgabi4488** [taufik-nurrohman/color-picker#68]
Hi guys,
I have a weird issue the change hook is running on plugin initializing, here is the test i did:

``` js
// Initialization
let picker = new CP(element);

// change hook listener
picker.on('change', function(r, g, b, a) {
    // firing immediately 
    console.log(1);
});
```

**Comment by taufik-nurrohman** [comment]
That&rsquo;s intentional. The `change` hook will also run on init to tidy/validate the color value. You can disable this effect by adding a placeholder variable to store the initialization state once.

~~~ .js
let init = true;

picker.on('change', function(r, g, b, a) {
    if (init) {
        return;
    }
    console.log([r, g, b, a]);
    init = false; // Update the state here!
});
~~~

**Comment by mgabi4488** [comment]
Thanks, that's exactly how i solved the issue.

**Comment by taufik-nurrohman** [comment]
FYI, you can also make custom hook inside another gook. For your case, that would be something like this:

~~~ .js
function onStart(r, g, b, a) {
    this.fire('start', [r, g, b, a]);
    this.off('change', onStart);
}

​picker​.​on​(​'change'​,​ ​onStart)​;
~~~

Later, you can trigger your initialization function via the `start` hook:

~~~ .js
picker.on('start', function(r, g, b, a) {
    console.log('Once!');
});
~~~

**Comment by evolross** [comment]
This seems weird. Why would we need to design around a test/validation? It's not logical that `changed` fires when the picker gets instantiated. Although it works well, your color picker package is very cumbersome to use with lots of strange work-arounds.

**Comment by taufik-nurrohman** [comment]
> It's not logical that `changed` fires when the picker gets instantiated.

There&rsquo;s a `drag` event that you can use to prevent this behaviour if you want.
