### ISSUE TITLE
Event listener firing on page load

### ISSUE THREAD

**Issue by tdiprima** [taufik-nurrohman/color-picker#69]
Hello @taufik-nurrohman,

I hope you can help me.  I need the color picker to fire on `change`, only.  And stay quiet on page load.

For other functions, I've used `addEventListener` with `bind`, in order to keep if from firing on page load.  But in the case of color-picker, it looks like we can't do that.

Or can we?  Am I missing something?

Thanks in advance!

**Comment by taufik-nurrohman** [comment]
The #68 issue may help. You cannot use native event listener here because this plugin uses custom event system.

**Comment by tdiprima** [comment]
#68 helped a lot.  Thanks! 😄
